### ISSUE TITLE
After upgrading to spring boot 2.0.0.M2 app is not working

### ISSUE THREAD

**Issue by rajadilipkolli** [danielfernandez/reactive-matchday#2]
I have upgraded spring boot version to 2.0.0.M2 and made necessary changes in Data.class in lines 318-321 as capped method signature is changed as below

 ```
 .then(mongoTemplate.createCollection(
                                MatchEvent.class, CollectionOptions.empty().capped().size(104857600))) // max: 100MBytes
                        .then(mongoTemplate.createCollection(
                                MatchComment.class, CollectionOptions.empty().capped().size(104857600))) // max: 100MBytes
```
                       
When I run the application it is starting with out error but when I hit localhost:8080 I get below error

```
2017-07-13 12:59:16.899  WARN 27472 --- [ctor-http-nio-2] i.n.u.concurrent.AbstractEventExecutor   : A task raised an exception. Task: reactor.ipc.netty.channel.ContextHandler$$Lambda$580/683007669@2fd7b40f

java.lang.NoSuchMethodError: org.thymeleaf.spring5.view.reactive.ThymeleafReactiveViewResolver.getApplicationContext()Lorg/springframework/context/ApplicationContext;
	at org.thymeleaf.spring5.view.reactive.ThymeleafReactiveViewResolver.loadView(ThymeleafReactiveViewResolver.java:581) ~[thymeleaf-spring5-3.0.6.M4.jar:3.0.6.M4]
	at org.thymeleaf.spring5.view.reactive.ThymeleafReactiveViewResolver.resolveViewName(ThymeleafReactiveViewResolver.java:569) ~[thymeleaf-spring5-3.0.6.M4.jar:3.0.6.M4]
	at org.springframework.web.reactive.result.view.ViewResolutionResultHandler.lambda$resolveViews$2(ViewResolutionResultHandler.java:272) ~[spring-webflux-5.0.0.RC2.jar:5.0.0.RC2]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:350) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:205) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:89) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:54) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxConcatMap.subscribe(FluxConcatMap.java:117) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoCollectList.subscribe(MonoCollectList.java:57) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:59) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoFlatMap$ThenMapMain.onNext(MonoFlatMap.java:146) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:1472) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1288) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:1162) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoSwitchIfEmpty.subscribe(MonoSwitchIfEmpty.java:44) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:59) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoFlatMap$ThenMapMain.onNext(MonoFlatMap.java:146) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:919) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoFlatMap$ThenMapInner.onNext(MonoFlatMap.java:229) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:919) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoThenIgnore$ThenAcceptInner.onNext(MonoThenIgnore.java:276) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:72) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:185) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:919) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoFlatMap$ThenMapMain.onNext(MonoFlatMap.java:140) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:919) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoWhen$WhenCoordinator.signal(MonoWhen.java:245) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoWhen$WhenInner.onNext(MonoWhen.java:299) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:185) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:1472) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:128) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoWhen$WhenInner.onSubscribe(MonoWhen.java:289) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:161) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:77) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoWhen$WhenCoordinator.subscribe(MonoWhen.java:174) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoWhen.subscribe(MonoWhen.java:124) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:59) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:77) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoThenIgnore$ThenIgnoreMain.drain(MonoThenIgnore.java:147) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoThenIgnore.subscribe(MonoThenIgnore.java:55) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoFlatMap$ThenMapMain.onNext(MonoFlatMap.java:146) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:265) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:767) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:115) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:1472) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:156) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1288) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:1162) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:409) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:205) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:89) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:54) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxConcatMap.subscribe(FluxConcatMap.java:117) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoNext.subscribe(MonoNext.java:40) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoSwitchIfEmpty.subscribe(MonoSwitchIfEmpty.java:44) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:59) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:59) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoThenIgnore$ThenIgnoreMain.drain(MonoThenIgnore.java:165) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoThenIgnore.subscribe(MonoThenIgnore.java:55) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoPeekTerminal.subscribe(MonoPeekTerminal.java:60) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.ipc.netty.channel.ChannelOperations.applyHandler(ChannelOperations.java:382) ~[reactor-netty-0.6.4.RELEASE.jar:0.6.4.RELEASE]
	at reactor.ipc.netty.http.server.HttpServerOperations.onHandlerStart(HttpServerOperations.java:354) ~[reactor-netty-0.6.4.RELEASE.jar:0.6.4.RELEASE]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.12.Final.jar:4.1.12.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [netty-common-4.1.12.Final.jar:4.1.12.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) [netty-transport-4.1.12.Final.jar:4.1.12.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.12.Final.jar:4.1.12.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
```

Can you please fix the issue

**Comment by rajadilipkolli** [comment]
Ping @danielfernandez

**Comment by danielfernandez** [comment]
Unfortunately (as you can see) there is an incompatibility between Spring Framework `5.0.0.RC2` (the version of Spring used by Spring Boot `2.0.0.M2`) and Thymeleaf-Spring5 `3.0.6.M4` (the version of Thymeleaf used by Spring Boot `2.0.0.M2`), so there is no real point in upgrading the `master` branch in this app (which uses Spring Boot `2.0.0.M1`) to `2.0.0.M2`.

The `dev` branch in this repository, however, uses Spring Boot `2.0.0.BUILD-SNAPSHOT` (with Spring Framework `5.0.0.BUILD-SNAPSHOT`) and Thymeleaf-Spring5 `3.0.7-SNAPSHOT`, which work along nicely. Also note that trying to use Spring Boot `2.0.0.M2` along with Thymeleaf `3.0.7-SNAPSHOT` is of no use either because there were breaking API changes in Spring Framework between `5.0.0.RC2` and the current `5.0.0.BUILD-SNAPSHOT` to which the Thymeleaf current snapshot had to adapt.

Spring Framework `5.0.0.RC3` should be published in a matter of days (AFAIK), and right after it is published I will publish Thymeleaf (+ Thymeleaf-Spring5) `3.0.7`. Some days later, Spring Boot `2.0.0.M3` will be published using both new versions (Spring's and Thymeleaf's), and at that moment upgrading to the latest *milestone* version of Spring Boot will be safe again for the `master` branch of this project.

**Comment by rajadilipkolli** [comment]
Thank you for the update this is very informative.

**Comment by danielfernandez** [comment]
Please note the `master` branch has been updated to Spring Boot `2.0.0.M3` (and Thymeleaf `3.0.7`).

**Comment by rajadilipkolli** [comment]
@danielfernandez Now with latest version it is working as per ReadMe.md except that I receive NPE when I navigate back from see match page to main page(http://localhost:8080/) 

Below is the stacktrace

Thread-19] org.mongodb.driver.connection           Callback onResult call produced an error

```
java.lang.NullPointerException: null
	at com.mongodb.operation.AsyncQueryBatchCursor$CommandResultSingleResultCallback.onResult(AsyncQueryBatchCursor.java:255) ~[mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.operation.AsyncQueryBatchCursor$CommandResultSingleResultCallback.onResult(AsyncQueryBatchCursor.java:235) ~[mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49) [mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor$1.onResult(DefaultServer.java:185) [mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49) [mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.connection.CommandProtocol$CommandResultCallback.callCallback(CommandProtocol.java:271) [mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.connection.ResponseCallback.onResult(ResponseCallback.java:48) [mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.connection.ResponseCallback.onResult(ResponseCallback.java:23) [mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.connection.DefaultConnectionPool$PooledConnection$2.onResult(DefaultConnectionPool.java:470) [mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.connection.DefaultConnectionPool$PooledConnection$2.onResult(DefaultConnectionPool.java:464) [mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.connection.UsageTrackingInternalConnection$3.onResult(UsageTrackingInternalConnection.java:119) [mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.connection.UsageTrackingInternalConnection$3.onResult(UsageTrackingInternalConnection.java:115) [mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49) [mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.connection.InternalStreamConnection.executeCallbackAndReceiveResponse(InternalStreamConnection.java:378) [mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.connection.InternalStreamConnection.access$1700(InternalStreamConnection.java:66) [mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.connection.InternalStreamConnection$ResponseBuffersCallback.onResult(InternalStreamConnection.java:420) [mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.connection.InternalStreamConnection$ResponseBuffersCallback.onResult(InternalStreamConnection.java:389) [mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.connection.InternalStreamConnection$ResponseHeaderCallback.onSuccess(InternalStreamConnection.java:562) [mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.connection.InternalStreamConnection$ResponseHeaderCallback.access$2200(InternalStreamConnection.java:517) [mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.connection.InternalStreamConnection$ResponseHeaderCallback$ResponseBodyCallback.onResult(InternalStreamConnection.java:584) [mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.connection.InternalStreamConnection$ResponseHeaderCallback$ResponseBodyCallback.onResult(InternalStreamConnection.java:568) [mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.connection.InternalStreamConnection$3.completed(InternalStreamConnection.java:447) [mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.connection.InternalStreamConnection$3.completed(InternalStreamConnection.java:444) [mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.connection.AsynchronousSocketChannelStream$BasicCompletionHandler.completed(AsynchronousSocketChannelStream.java:218) [mongodb-driver-core-3.4.2.jar:na]
	at com.mongodb.connection.AsynchronousSocketChannelStream$BasicCompletionHandler.completed(AsynchronousSocketChannelStream.java:201) [mongodb-driver-core-3.4.2.jar:na]
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126) [na:1.8.0_101]
	at sun.nio.ch.Invoker$2.run(Invoker.java:218) [na:1.8.0_101]
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112) [na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
```

**Comment by danielfernandez** [comment]
That is a known bug in the reactive MongoDB Java driver. It's supposed to be fixed in their next version.
